export const API_ENDPOINTS = {
  AUTH: {
    CSRF_TOKEN: '/csrf-token',
    LOGIN: '/auth/login',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_OTP: '/auth/verify-otp',
    SEND_OTP: '/auth/send-otp',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    STATUS: (id: string) => `/users/${id}/status`,
    TEACHERS: '/users/teachers',
    ADMIN: '/users/admin',
    CREATE_TEACHER: '/users/teacher',
    CREATE_STUDENT: '/users/student',
    PROFILE: '/users/profile',
    PROFILE_IMAGE: '/users/profile-image',
  },
  INSTITUTES: {
    BASE: '/institutes',
    BY_ID: (id: string) => `/institutes/${id}`,
  },
  COURSES: {
    BASE: '/courses',
    BY_ID: (id: string) => `/courses/${id}`,
    THUMBNAIL: (id: string) => `/courses/${id}/thumbnail`,
    TEMPLATE: (id: string) => `/courses/${id}/template`,
    MY_COURSES: '/courses/my-courses',
  },
  ENROLLMENTS: {
    BASE: '/enrollments',
    COURSE_STUDENTS: (courseId: string) => `/enrollments/course/${courseId}/students`,
    STUDENT_ENROLLMENT: (courseId: string, studentId: string) => `/enrollments/${courseId}/students/${studentId}`,
    TEACHER: '/enrollments/teacher',
    MY_COURSES: '/enrollments/my-courses',
  },
  STUDY_MATERIALS: {
    BY_COURSE: (courseId: string) => `/study-materials/course/${courseId}`,
    BY_ID: (id: string) => `/study-materials/${id}`,
  },
  LECTURES: {
    BY_COURSE: (courseId: string) => `/lectures/course/${courseId}`,
    BY_ID: (id: string) => `/lectures/${id}`,
    RECORDING: (id: string) => `/lectures/${id}/recording`,
    RECORDING_UPLOAD_URL: (id: string) => `/lectures/${id}/recording/upload-url`,
    RECORDING_CONFIRM: (id: string) => `/lectures/${id}/recording/confirm`,
    THUMBNAIL: (id: string) => `/lectures/${id}/thumbnail`,
  },
  ATTENDANCE: {
    BY_LECTURE: (lectureId: string) => `/attendance/lecture/${lectureId}`,
    EXPORT: (lectureId: string) => `/attendance/lecture/${lectureId}/export`,
    MARK: (lectureId: string) => `/attendance/lecture/${lectureId}/mark`,
    MY: '/attendance/my',
  },
  ASSIGNMENTS: {
    BY_COURSE: (courseId: string) => `/assignments/course/${courseId}`,
    BY_ID: (id: string) => `/assignments/${id}`,
    SUBMIT: (id: string) => `/assignments/${id}/submit`,
    SUBMISSIONS: (id: string) => `/assignments/${id}/submissions`,
    GRADE: (submissionId: string) => `/assignments/submission/${submissionId}/grade`,
    ADMIN_ALL: '/assignments/admin/all',
    TEACHER_ALL: '/assignments/teacher/all',
    TEACHER_RECENT: '/assignments/teacher/recent',
    STUDENT: '/assignments/student',
    MY_TASKS: '/assignments/my-tasks',
    MY_SUBMISSIONS: '/assignments/my-submissions',
  },
  QUIZZES: {
    BY_COURSE: (courseId: string) => `/quizzes/course/${courseId}`,
    BY_ID: (id: string) => `/quizzes/${id}`,
    SUBMISSIONS: (id: string) => `/quizzes/${id}/submissions`,
    SUBMIT: (id: string) => `/quizzes/${id}/submit`,
    GENERATE_AI: '/quizzes/generate-ai',
  },
  DISCUSSIONS: {
    BY_COURSE: (courseId: string) => `/discussions/course/${courseId}`,
    BY_ID: (id: string) => `/discussions/${id}`,
    REPLY: (id: string) => `/discussions/${id}/reply`,
    PIN: (id: string) => `/discussions/${id}/pin`,
    MY_DISCUSSIONS: '/discussions/my-discussions',
    ALL: '/discussions/all',
  },
  COMMUNICATIONS: {
    MESSAGES_BY_ID: (id: string) => `/communications/messages/${id}`,
    GROUP_BY_ID: (id: string) => `/communications/groups/${id}`,
    CONTACTS: '/communications/contacts',
    SEND_MESSAGE: '/communications/messages',
    CREATE_GROUP: '/communications/groups',
    ANNOUNCEMENTS: '/communications/announcements',
    MY_ANNOUNCEMENTS: '/announcements/my',
  },
  PROGRESS: {
    BY_COURSE: (courseId: string) => `/progress/course/${courseId}`,
    STUDENT_PERFORMANCE: '/analytics/student/performance',
  },
  CERTIFICATES: {
    GENERATE: (courseId: string) => `/certificates/generate/${courseId}`,
    MY: '/certificates/my',
  },
  ANALYTICS: {
    ADMIN_BASE: '/analytics/admin',
    ADMIN_STATS: '/analytics/admin/stats',
    ADMIN_REPORTS: '/analytics/admin/reports',
    ADMIN_ENROLLMENT_TREND: '/analytics/admin/enrollment-trend',
    TEACHER_BASE: '/analytics/teacher',
    TEACHER_WEEKLY: '/analytics/teacher/weekly',
    TEACHER_STATS: '/analytics/teacher/stats',
    TEACHER_REPORTS: '/analytics/teacher/reports',
    STUDENT_BASE: '/analytics/student',
    STUDENT_STATS: '/analytics/student/stats',
    STUDENT_PERFORMANCE: '/analytics/student/performance',
    LEADERBOARD: '/analytics/student/leaderboard',
  },
  ACTIVITY: {
    ADMIN_RECENT: '/activity/admin/recent',
    RECENT: '/activity/recent',
  },
  INTEGRATIONS: {
    BASE: '/integrations',
    BY_ID: (id: string) => `/integrations/${id}`,
    SEED: '/integrations/seed',
  },
  NOTIFICATIONS: {
    MY: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    DELETE: (id: string) => `/notifications/${id}`,
    SUBSCRIBE: '/notifications/subscribe',
    PUBLIC_KEY: '/notifications/public-key',
  },
  LIVE_CLASSES: {
    UPCOMING: '/live-classes/upcoming',
  }
};
